name: Build only

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake
          brew install pkgconf
          brew install autoconf
          brew install automake
          brew install libtool
          python3 -m pip install --break-system-packages meson==1.4.2
          brew install ninja
          brew install rename

      - name: Install Rust (nightly)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          ~/.cargo/bin/rustup install nightly
          ~/.cargo/bin/rustup component add rust-src --toolchain nightly

      - name: Add Cargo to PATH
        run: echo "${HOME}/.cargo/bin" >> $GITHUB_PATH

      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Prepare gradle
        run: chmod +x ./gradlew

      - name: shaderc
        run: ./gradlew assemble[shaderc] --info --stacktrace

      - name: spirvcross
        run: ./gradlew assemble[spirvcross] --info --stacktrace

      - name: vulkan
        run: ./gradlew assemble[vulkan] --info --stacktrace

      - name: dovi
        run: ./gradlew assemble[dovi] --info --stacktrace

      - name: lcms2
        run: ./gradlew assemble[littlecms2]--info --stacktrace

      - name: dav1d
        run: ./gradlew assemble[dav1d] --info --stacktrace

      - name: placebo
        run: ./gradlew assemble[placebo] --info --stacktrace

      - name: uchardet
        run: ./gradlew assemble[uchardet] --info --stacktrace

      - name: unibreak
        run: ./gradlew assemble[unibreak] --info --stacktrace

      - name: fribidi
        run: ./gradlew assemble[fribidi] --info --stacktrace

      - name: freetype
        run: ./gradlew assemble[freetype] --info --stacktrace

      - name: harfbuzz
        run: ./gradlew assemble[harfbuzz] --info --stacktrace

      - name: mbedtls
        run: ./gradlew assemble[mbedtls] --info --stacktrace

      - name: ass
        run: ./gradlew assemble[ass] --info --stacktrace

      - name: ffmpeg
        run: ./gradlew assemble[ffmpeg] --info --stacktrace

      - name: mpv
        run: ./gradlew assemble[mpv] --info --stacktrace

      - name: Test binaries load & interop on jvm
        run: ./gradlew test-jvm:test
